parameters:
  Capacity: 2.5
  NumberOfCellsConnectedInSeries: 1
  StandardVoltageCell: 3.7 
  LowerCutoffVoltage: 3
  UpperCutoffVoltage: 4.2

# list of instructions to follow sequentially
instructions: 
    - sequence:
        - type: current
          value: -1
          unit: C
          termination:
               - type: voltage
                 value: UpperCutoffVoltage
        - type: voltage
          value: 4.2
          termination:
               - type: current
                 value: 0.1
        - type: rest
          time: 3600
      name: CCCV charge
      repeat: 1